### ISSUE TITLE
Hot to connect to an application in other docker instance

### ISSUE THREAD

**Issue by SteffenGorenflo** [therealpadams/moskito#1]
Every time I start up my moskito docker instance and try to connect to my java application (tomcat, web server, running in a different docker container), I get the following error:

![image](https://user-images.githubusercontent.com/5612074/28157837-13a0f8b8-67b8-11e7-9546-f2d5eb63c7bf.png)

````Cannot connect to localhost@localhost:9401, due: Can not resolve manually set reference. Server at localhost, port: 9401 is down or not properly configured````

Can you please provide me some information on how to configure properly my docker instances.

I exposed the port 9401 in the web docker container and set the correct jvm options (`-DlocalRmiRegistryPort=9401`)

**Comment by baggerspion** [comment]
I don't _know_, but my guess is this.. The most likely issue here is your use of "localhost", this will only work if:
- both containers are running on the same machine
- they were both started using host networking

Instead of providing `localhost:9401`, try providing the IP of the machine you are exposing the port on.

**Comment by SteffenGorenflo** [comment]
your guess was right ;)

I needed to provide the name of the container where my application is running (`api:9401` in my case). 

Thanks for your help
